name: Static Application Security Testing (SAST)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt -t .

      - name: Check Python and pip versions
        run: |
          which python
          python --version
          which pip
          pip --version
   

      - name: Run SAST
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python analyze_code.py sample-code.py 
